### ISSUE TITLE
Text flashes continuously when typing

### ISSUE THREAD

**Issue by tuhdo** [Fanael/rainbow-identifiers#2]
When we type, text keeps flashing with colors, which looks kinda annoying. Maybe we should have a timer, so users have an interval between the recently typed character and the next character to type. During this interval, identifier won't change its color. If no typing is made during this interval, the identifier is considered complete and change its color.

**Comment by Fanael** [comment]
To be frank, in my opinion it's not a bug, it's just the way `font-lock-mode` works. You can change that by modifying `jit-lock` options, but changes will pertain to _all_ highlighting.

At any rate, patches are welcome.

**Comment by tuhdo** [comment]
I delay highlighting by modifying `jit-lock-defer-time` to a low value like 0.1. But I guess someone will by annoyed by not having their text highlighted immediately. I think you should note about `jit-lock-defer-time` in the README.

**Comment by Fanael** [comment]
> I think you should note about `jit-lock-defer-time` in the README.

Unlikely. The right place for `jit-lock` settings is the Emacs manual.

**Comment by tuhdo** [comment]
Well, not everyone know about such thing in the first place.

**Comment by Fanael** [comment]
Sure, but `font-lock-mode` tuning is outside the purview of `rainbow-identifiers`.

**Comment by ksjogo** [comment]
On Mac I did not really notice the flashing, on windows it is more notable for some reason. Did you have any idea in the mean time how to keep the currently cursored word stable?
