### ISSUE TITLE
Could you add support for Idris?

### ISSUE THREAD

**Issue by pharpend** [Fanael/rainbow-identifiers#3]
Idris is a functional language, much like Haskell. This mode doesn't seem to do anything in `idris-mode`.

I'm not sure if this is a bug in `idris-mode` or in `rainbow-identifiers`

**Comment by Fanael** [comment]
`idris-mode` fontifies all identifiers with `idris-identifier-face`, so you need to add this face to `rainbow-identifiers-faces-to-override`.

**Comment by pharpend** [comment]
Alright, thank you!
